apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.externaldnsOperator.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  MONITOR_SERVICE_REF: "{{ .Values.externaldnsOperator.monitorServiceRef }}"