# Default values for traefik-external-dns-controller
# This is a YAML-formatted file.

# Controller configuration
controller:
  # Image configuration
  image:
    repository: ybucci/traefik-external-dns-controller
    pullPolicy: IfNotPresent
    tag: "2.1.1"

  # Environment variables
  env:
    # Dynamic service configuration (JSON format)
    # Example:
    # servicesConfig: |
    #   {
    #     "external": {
    #       "namespace": "traefik",
    #       "name": "traefik-external",
    #       "default": true,
    #       "annotations": {
    #         "traefik.io/external": "true"
    #       }
    #     },
    #     "internal": {
    #       "namespace": "traefik",
    #       "name": "traefik-internal",
    #       "default": false,
    #       "annotations": {
    #         "traefik.io/internal": "true"
    #       }
    #     }
    #   }
    servicesConfig: |
      {
        "external": {
          "namespace": "traefik",
          "name": "traefik",
          "default": true,
          "annotations": {
            "traefik.io/external": "true"
          }
        },
        "internal": {
          "namespace": "traefik",
          "name": "traefik-internal",
          "default": false,
          "annotations": {
            "traefik.io/internal": "true"
          }
        }
      }

  # Resource limits and requests
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Security context
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Annotations for the deployment
  annotations: {}

  # Labels for the deployment
  labels: {}

# Service Account
serviceAccount:
  # Create a service account
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true
  # Annotations to add to the RBAC resources
  annotations: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Common labels
commonLabels: {}

# Common annotations
commonAnnotations: {}

# Image pull secrets
imagePullSecrets: []

# Deployment strategy
strategy:
  type: Recreate

# Liveness and readiness probes (hardcoded to port 8080 in controller)
livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

# Pod security context
podSecurityContext:
  fsGroup: 0
