# Example values for traefik-external-dns-controller
# This demonstrates common configuration scenarios

# ---
# Dynamic Service Configuration (Recommended)
# Basic external + internal setup with default-based selection
controller:
  env:
    servicesConfig: |
      {
        "external": {
          "namespace": "traefik",
          "name": "traefik-external",
          "default": true,
          "annotations": {
            "traefik.io/external": "true"
          }
        },
        "internal": {
          "namespace": "traefik",
          "name": "traefik-internal",
          "default": false,
          "annotations": {
            "traefik.io/internal": "true"
          }
        }
      }

# ---
# Multi-Environment Configuration
# controller:
#   env:
#     servicesConfig: |
#       {
#         "production": {
#           "namespace": "traefik-prod",
#           "name": "traefik-production",
#           "default": true,
#           "annotations": {
#             "traefik.io/environment": "production"
#           }
#         },
#         "staging": {
#           "namespace": "traefik-staging",
#           "name": "traefik-staging",
#           "default": false,
#           "annotations": {
#             "traefik.io/environment": "staging"
#           }
#         },
#         "development": {
#           "namespace": "traefik-dev",
#           "name": "traefik-dev",
#           "default": false,
#           "annotations": {
#             "traefik.io/environment": "development"
#           }
#         }
#       }

# ---
# Multi-Region Configuration
# controller:
#   env:
#     servicesConfig: |
#       {
#         "us-east": {
#           "namespace": "traefik-us-east",
#           "name": "traefik-us-east",
#           "default": true,
#           "annotations": {
#             "traefik.io/region": "us-east"
#           }
#         },
#         "us-west": {
#           "namespace": "traefik-us-west",
#           "name": "traefik-us-west",
#           "default": false,
#           "annotations": {
#             "traefik.io/region": "us-west"
#           }
#         },
#         "eu-central": {
#           "namespace": "traefik-eu",
#           "name": "traefik-eu-central",
#           "default": false,
#           "annotations": {
#             "traefik.io/region": "eu-central"
#           }
#         }
#       }

# ---
# Production configuration with resource limits
# controller:
#   env:
#     servicesConfig: |
#       {
#         "external": {
#           "namespace": "traefik",
#           "name": "traefik-external",
#           "default": true,
#           "annotations": {
#             "traefik.io/external": "true"
#           }
#         },
#         "internal": {
#           "namespace": "traefik",
#           "name": "traefik-internal",
#           "default": false,
#           "annotations": {
#             "traefik.io/internal": "true"
#           }
#         }
#       }
#     kopfLogLevel: "WARNING"
#     reconcileIntervalSeconds: 60
#   resources:
#     limits:
#       cpu: 500m
#       memory: 512Mi
#     requests:
#       cpu: 200m
#       memory: 256Mi
#   nodeSelector:
#     node-role.kubernetes.io/control-plane: ""
#   tolerations:
#   - key: node-role.kubernetes.io/control-plane
#     operator: Exists
#     effect: NoSchedule

# ---
# Debug configuration
# controller:
#   env:
#     servicesConfig: |
#       {
#         "external": {
#           "namespace": "traefik",
#           "name": "traefik-external",
#           "default": true,
#           "annotations": {
#             "traefik.io/external": "true"
#           }
#         }
#       }
#     kopfLogLevel: "DEBUG"
# config:
#   debug: true
#   dryRun: true  # Only log changes, don't apply them

# ---
# Monitoring configuration
# monitoring:
#   prometheus:
#     enabled: true
#     port: 9090
#     path: /metrics
#   serviceMonitor:
#     enabled: true
#     namespace: monitoring
#     labels:
#       release: prometheus

# ---
# Single replica configuration (default behavior)
# Note: Controller is designed to run as single replica to avoid conflicts
# Multiple replicas are not supported due to lack of leader election
# replicaCount: 1  # This is enforced in the deployment template
