{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "traefik-external-dns-controller.fullname" . }}
  labels:
    {{- include "traefik-external-dns-controller.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "traefik-external-dns-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "traefik-external-dns-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }} 