{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "traefik-external-dns-controller.fullname" . }}
  labels:
    {{- include "traefik-external-dns-controller.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
# Services permissions
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# IngressRoute permissions (traefik.io)
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes"]
  verbs: ["get", "list", "watch", "patch", "update"]
# IngressRoute permissions (traefik.containo.us - legacy API group)
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["get", "list", "watch", "patch", "update"]
# Events permissions for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# Kopf framework permissions
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# CRD discovery permissions for Kopf
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
{{- end }} 