apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik-external-dns-controller.fullname" . }}-config
  labels:
    {{- include "traefik-external-dns-controller.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  SERVICES_CONFIG: {{ .Values.controller.env.servicesConfig | quote }} 